# Source: cluster-api-aws/templates/rbac.yaml
apiVersion: rbac.authorization.k8s.io/v1
kind: RoleBinding
metadata:
  name: c8n7x24ty-capi-aws
  namespace: c8n7x24ty
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: Role
  name: c8n7x24ty-capi-aws
subjects:
- kind: ServiceAccount
  name: c8n7x24ty-capi-aws
